name: the_crew_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  image_picker: ^1.0.1
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.6.2
  provider: ^6.0.5  # Add this line for state management
  cached_network_image: ^3.2.0
  photo_view: ^0.14.0
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.0
  google_place: ^0.4.7
  intl: ^0.17.0  # Add this line
  # share_plus: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # Add your asset files here, for example:
    # - assets/images/
    # - assets/icons/

  # Add any other assets or fonts you might need here