// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1F8CVRM4G7XnJDaT20fzpPwksLP6L_dA',
    appId: '1:218958953338:android:1ecebd3d457da127bcf4c3',
    messagingSenderId: '218958953338',
    projectId: 'the-crew-flutter-app',
    storageBucket: 'the-crew-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDceTIcmvJ6mKbxAQysR6KfGA-_7QXeakA',
    appId: '1:218958953338:ios:8a63e0519c96f115bcf4c3',
    messagingSenderId: '218958953338',
    projectId: 'the-crew-flutter-app',
    storageBucket: 'the-crew-flutter-app.appspot.com',
    iosBundleId: 'com.example.theCrewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDceTIcmvJ6mKbxAQysR6KfGA-_7QXeakA',
    appId: '1:218958953338:ios:8a63e0519c96f115bcf4c3',
    messagingSenderId: '218958953338',
    projectId: 'the-crew-flutter-app',
    storageBucket: 'the-crew-flutter-app.appspot.com',
    iosBundleId: 'com.example.theCrewApp',
  );

}